apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
        - name: myproject
          image: 'ajayrajsingh31/myproject:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: mydatabase
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: '3306'
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
      volumes:
        - name: static-files
          emptyDir: {}
